##############################################################
##             Physical synthesis commands                  ##
## Script Generated for Undergrad class of microelectronics ##
## Generated by Fernando Moraes 05/junho/2022               ##
## Updated by Fernando Moraes 03/novembre/2025              ##
##############################################################

set_distributed_hosts -local
set_multi_cpu_usage -local_cpu max -remote_host 1 -cpu_per_remote_host 28

set TOP_MODULE nanoCPU

set_db init_power_nets {vdd}
set_db init_ground_nets {gnd}    

read_db nanoCPU_genus.db

connect_global_net vdd -type pg_pin -pin_base_name vdd -inst_base_name *
connect_global_net gnd -type pg_pin -pin_base_name gnd -inst_base_name *
connect_global_net vdd -type tie_hi -inst_base_name *
connect_global_net gnd -type tie_lo -inst_base_name *

##Generating square floorplan (1) with 80% of density (0.85) with 3um margins 
create_floorplan -site CORE12T -core_density_size 1 0.85 3 3 3 3 

gui_fit

##Generate power ring with 0.25um spacing (between metal lines), 0.5um width and 1.5um offset from the core. Use M1 for horizontal and M2 for vertical
add_rings -spacing 0.25 -width 0.5 -layer {top M2 bottom M2 left M1 right M1} -jog_distance 2.5 -offset 1.5 -nets {gnd vdd} -threshold 2.5

##Route power rails using M1
route_special -connect {block_pin pad_pin pad_ring core_pin floating_stripe} -layer_change_range { M1(1) LB(11) } -block_pin_target nearest_target -pad_pin_port_connect {all_port one_geom} -pad_pin_target nearest_target -core_pin_target first_after_row_end -floating_stripe_target {block_ring pad_ring ring stripe ring_pin block_pin followpin} -allow_jogging 1 -crossover_via_layer_range { M1(1) LB(11) } -nets { gnd vdd } -allow_layer_change 1 -block_pin use_lef -target_via_layer_range { M1(1) LB(11) }

##Add well taps
add_well_taps -cell  C12T28SOI_LR_FILLERNPW4 -cell_interval 20 -fixed_gap -prefix WELLTAP -in_row_offset 6.0

##Add power stripes
add_stripes -block_ring_top_layer_limit M3 -max_same_layer_jog_length 6 -pad_core_ring_bottom_layer_limit M1 -set_to_set_distance 25 -pad_core_ring_top_layer_limit M3 -spacing 4 -merge_stripes_value 2.5 -layer M1 -block_ring_bottom_layer_limit M1 -width 0.4 -nets {gnd vdd}

gui_fit

# Place pins in the chip sides
set_db assign_pins_edit_in_batch true
edit_pin -fix_overlap 1 -unit micron -spread_direction clockwise -side Left   -layer 2 -spread_type center -spacing 1.0 -pin {ck rst}
#edit_pin -fix_overlap 1 -unit micron -spread_direction clockwise -side Bottom  -layer 2 -spread_type center -spacing 1.0 -pin {}
edit_pin -fix_overlap 1 -unit micron -spread_direction clockwise -side Top    -layer 3 -spread_type center -spacing 1.0 -pin {address*}
edit_pin -fix_overlap 1 -unit micron -spread_direction clockwise -side Right  -layer 3 -spread_type center -spacing 1.0 -pin {dataR* dataW* ce we}
set_db assign_pins_edit_in_batch false

# posionamento
place_opt_design

## Clock tree synthesiscd 
clock_opt_design

#roteamento
route_design
route_design -global_detail -wire_opt
set_db timing_analysis_type ocv
opt_design -post_route


##Add filler cells
set FILLER_CELLS {C12T28SOI_LR_FILLERNPW4 C12T28SOI_LR_FILLERCELL1 C12T28SOI_L_FILLERCELL1 C12T28SOI_L_FILLERCELL2  C12T28SOI_LR_FILLERPFOP2 C12T28SOI_LR_FILLERPFOP4  C12T28SOI_LR_FILLERPFOP8 C12T28SOI_LR_FILLERPFOP16  C12T28SOI_LR_FILLERPFOP32 C12T28SOI_LR_FILLERPFOP64 C12T28SOI_LR_FILLERFLPCHKAE16  C12T28SOI_LR_FILLERFLPCHKAE2 C12T28SOI_LR_FILLERFLPCHKAE32 C12T28SOI_LR_FILLERFLPCHKAE4 C12T28SOI_LR_FILLERFLPCHKAE64  C12T28SOI_LR_FILLERFLPCHKAE8 }
add_fillers -base_cells $FILLER_CELLS -prefix FILLER

##verify design
check_drc

##Generate reports
report_summary -out_dir summaryReport

## Gera arquivo para simulação SDF
extract_rc
write_sdf nano_pr.sdf
write_netlist nano_pr.v

# Relatórios
report_area   > nano_pr.txt
report_gate_count  >> nano_pr.txt
report_timing  >> nano_pr.txt