##############################################################
##              Logical synthesis commands                  ##
## Script Generated for Undergrad class of microelectronics ##
## Generated by Fernando Moraes 05/junho/2022               ##
## Updated by Fernando Moraes 03/novembre/2025              ##
##############################################################

## 1) load synthesis configuration, read description and elaborate design 
include ./constraint/load.tcl
read_hdl -sv nanoCPU.sv
elaborate NanoCPU
set_db [current_design] .dft_dont_scan true

## 2) read constraints
read_sdc ./constraint/restrictions.sdc

## 3) synthesize to mapped
syn_generic
syn_map
syn_opt 

## 4) reports

report_area  > nano.txt
report_gates >> nano.txt
report_timing >> nano.txt
report_power  -unit mW >> nano.txt

## 5) build physical synthesis environment
write_netlist [current_design] > nano.v
write_db -common -all_root_attributes nanoCPU_genus.db
exit
